### ISSUE TITLE
onPlay and onPause are not getting called in 

### ISSUE THREAD

**Issue by martymiller** [googlesamples/leanback-assistant#1]
I'm using MediaSessiMediaSessionCompat.Callback and I can't get play/pause to work.

The callback inside of MediaSessionCompat successfully calls onSkipToNext(), onSkipToPrevious(), onSeekTo(), but it does not call onPlay() or onPause().

Please advise, thank you.

**Comment by Waleedasim** [comment]
same problem please guide

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
